version: "2"
networks:
  caliper-overlay:
    external:
      name: caliper-overlay

services:
  caliper_2.2:
    container_name: caliper_2.2
    image: hyperledger/caliper:0.4.1
    command: launch manager --caliper-fabric-gateway-enabled
    environment:
      - CALIPER_BIND_SUT=fabric:2.1.0
      - CALIPER_BENCHCONFIG=scenarios/config.yaml 
      - CALIPER_NETWORKCONFIG=networks/fabric/network-config3.yaml
    volumes:
      - ./caliper-benchmarks-local:/hyperledger/caliper/workspace
    networks:
      caliper-overlay:
        aliases:
          - caliper.digiblocks.com
    # deploy:
    #         placement:
    #             constraints: [node.hostname == instance-7]


