test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
  workers:
    type: local
    number: 5      #number of clients you need to spawn
  rounds:
      - label: createAsset
        description: Read asset benchmark
        txNumber: 1000
        rateControl: 
          type: fixed-load
          opts:
            transactionLoad: 40
        workload:
          module: scenarios/workload.js
          arguments:
            contractId: identitycontract

monitors:
  resource:
  - module: docker
    options:
      interval: 5
      containers:
      - all
    charting:
      bar:
        metrics: [Memory(avg), CPU%(avg)]
      polar:
        metrics: [all]

      