test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
  workers:
    type: local
    number: 1      #number of clients you need to spawn
  rounds:
      - label: createAsset
        description: Read asset benchmark
        txNumber: 10
        rateControl: 
          type: fixed-load
          opts:
            transactionLoad: 5
        workload:
          module: scenarios/workload.js
          arguments:
            contractId: identitycontract

      - label: Create Car
        txNumber: 50
        rateControl:
          type: fixed-rate
          opts:
            tps: 10
        workload:
          module: benchmarks/scenario/simple/pavan-v2.2/createCar.js

monitor:
  type:
  - docker
  docker:  
    containers:
    - http://localhost:7050/orderer.digiblocks.com
    - http://localhost:8050/orderer2.digiblocks.com
    - http://localhost:9050/orderer3.digiblocks.com
    - http://localhost:10050/orderer4.digiblocks.com
    - http://localhost:11050/orderer5.digiblocks.com
      