test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
  workers:
    type: local
    number: 5      #number of clients you need to spawn
  rounds:
      - label: createAsset
        description: Read asset benchmark
        txDuration: 30
        rateControl: 
          type: fixed-load
          opts:
            transactionLoad: 10
        workload:
          module: scenarios/workload.js
          arguments:
            contractId: identitycontract

  monitors:
    resource:
    - module: docker
      options:
        interval: 5
        containers:
        - http://10.128.0.27:7050/orderer.digiblocks.com
        - http://10.128.0.27:7051/peer0.org1.digiblocks.com
        - http://10.128.0.27:7054/ca.org1.digiblocks.com
        - http://10.128.0.27:5984/couchdb0
      charting:
        bar:
          metrics: [Memory(avg), CPU%(avg)]
        polar:
          metrics: [all]

      