test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
  workers:
    type: local
    number: 5      #number of clients you need to spawn
  rounds:
      - label: createAsset
        description: Read asset benchmark
        txDuration: 30
        rateControl: 
          type: fixed-load
          opts:
            transactionLoad: 10
        workload:
          module: scenarios/workload.js
          arguments:
            contractId: identitycontract