# Docker compose for multi-org-ca-1
#DEV_MODE_NET
version: '2'

networks:
  digiblocks:

services:

  # MSPs
  ca.digi-01.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.digi-01.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.digi-01.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.digi-01.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - "1054:1054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./../../crypto/crypto-config/peerOrganizations/digi-01.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./../../crypto/crypto-config/peerOrganizations/digi-01.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.digi-01.com
    networks:
      - digiblocks

  ca.digi-02.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.digi-02.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.digi-02.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.digi-02.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - "2054:2054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./../../crypto/crypto-config/peerOrganizations/digi-02.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./../../crypto/crypto-config/peerOrganizations/digi-02.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.digi-02.com
    networks:
      - digiblocks


  # Orderer
  orderer0.digiblocks.com:
    container_name: orderer0.digiblocks.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/digiblocks-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=1050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    volumes:
      - ./../../config/digiblocks-genesis.block:/var/hyperledger/orderer/digiblocks-genesis.block
      - ./../../crypto/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer0.digiblocks.com/msp:/var/hyperledger/orderer/msp
      - ./../../crypto/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer0.digiblocks.com/tls:/var/hyperledger/orderer/tls
      #- ../../config:/var/hyperledger/config
      #- ${HOME}/ledgers/orderer0.digiblocks.com:/var/ledger
    ports:
      - 1050:1050
      - 8443:8443
    networks:
      - digiblocks
      
  orderer1.digiblocks.com:
    container_name: orderer1.digiblocks.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/digiblocks-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=2050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    volumes:
      - ./../../config/digiblocks-genesis.block:/var/hyperledger/orderer/digiblocks-genesis.block
      - ./../../crypto/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer1.digiblocks.com/msp:/var/hyperledger/orderer/msp
      - ./../../crypto/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer1.digiblocks.com/tls:/var/hyperledger/orderer/tls
      #- ../../config:/var/hyperledger/config
      #- ${HOME}/ledgers/orderer0.digiblocks.com:/var/ledger
    ports:
      - 2050:2050
      - 8444:8443
    networks:
      - digiblocks

  orderer2.digiblocks.com:
    container_name: orderer2.digiblocks.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/digiblocks-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=3050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    volumes:
      - ./../../config/digiblocks-genesis.block:/var/hyperledger/orderer/digiblocks-genesis.block
      - ./../../crypto/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer2.digiblocks.com/msp:/var/hyperledger/orderer/msp
      - ./../../crypto/crypto-config/ordererOrganizations/digiblocks.com/orderers/orderer2.digiblocks.com/tls:/var/hyperledger/orderer/tls
      #- ../../config:/var/hyperledger/config
      #- ${HOME}/ledgers/orderer0.digiblocks.com:/var/ledger
    ports:
      - 3050:3050
      - 8445:8443
    networks:
      - digiblocks


  couchdb0:
      container_name: couchdb0
      image: hyperledger/fabric-couchdb
      environment:
        DB_URL: http://localhost:5984/member_db
        # - COUCHDB_USER=
        # - COUCHDB_PASSWORD=
      ports:
        - 5984:5984
      networks:
        - digiblocks      
  
  couchdb1:
      container_name: couchdb1
      image: hyperledger/fabric-couchdb
      environment:
        DB_URL: http://localhost:5984/member_db
        # - COUCHDB_USER=
        # - COUCHDB_PASSWORD=
      ports:
        - 6984:5984
      networks:
        - digiblocks      



  # DigiBlocks-01 peer0
  peer0.digi-01.com:
    container_name: peer0.digi-01.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Digi-01MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=digiblocks_test

      - CORE_PEER_ID=peer0.digi-01.com
      - CORE_PEER_ADDRESS=peer0.digi-01.com:1051
      # - CORE_PEER_ADDRESS=localhost:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:1051
      - CORE_PEER_CHAINCODEADDRESS=peer0.digi-01.com:1052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:1052
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.digi-01.com:1051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      
    # working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start

    volumes:
      - ./../../crypto/crypto-config/peerOrganizations/digi-01.com/peers/peer0.digi-01.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./../../crypto/crypto-config/peerOrganizations/digi-01.com/peers/peer0.digi-01.com/tls:/etc/hyperledger/crypto/peer/tls
      - ./../../config:/etc/hyperledger/channel
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      # - ${HOME}/ledgers/peer0.digi-01.com/:/var/ledger
    depends_on: 
      #- couchdb0
      - orderer0.digiblocks.com
    ports:
      - 1051:1051

    networks:
      - digiblocks


  # DigiBlocks-02 peer0
  peer0.digi-02.com:
    container_name: peer0.digi-02.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Digi-01MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=digiblocks_test

      - CORE_PEER_ID=peer0.digi-02.com
      - CORE_PEER_ADDRESS=peer0.digi-02.com:2051
      # - CORE_PEER_ADDRESS=localhost:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:2051
      - CORE_PEER_CHAINCODEADDRESS=peer0.digi-02.com:2052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:2052
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.digi-02.com:2051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      
    # working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start

    volumes:
      - ./../../crypto/crypto-config/peerOrganizations/digi-02.com/peers/peer0.digi-02.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./../../crypto/crypto-config/peerOrganizations/digi-02.com/peers/peer0.digi-02.com/tls:/etc/hyperledger/crypto/peer/tls
      - ./../../config:/etc/hyperledger/channel
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      # - ${HOME}/ledgers/peer0.digi-01.com/:/var/ledger
    depends_on: 
      #- couchdb1
      - orderer0.digiblocks.com
    ports:
      - 2051:2051

    networks:
      - digiblocks






  # # Budget peer1
  # budget-peer1.budget.com:
  #   container_name: budget-peer1.budget.com
  #   image: hyperledger/fabric-peer:$IMAGE_TAG
  #   environment:
  #     - FABRIC_CFG_PATH=/var/hyperledger/config
  #     # - CORE_LOGGING_LEVEL=debug
  #     - FABRIC_LOGGING_SPEC=DEBUG

  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_airline

  #     - CORE_PEER_ID=budget-peer1.budget.com
  #     - CORE_PEER_ADDRESS=budget-peer1.budget.com:8051
  #     # - CORE_PEER_LISTENADDRESS=budget-peer1.budget.com:8051
  #     - CORE_PEER_LISTENADDRESS=budget-peer1.budget.com:8051
  #     - CORE_PEER_CHAINCODELISTENADDRESS=budget-peer1.budget.com:8052
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=budget-peer1.budget.com:8051
  #     - CORE_PEER_LOCALMSPID=BudgetMSP
  #     - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
  #     - CORE_PEER_TLS_ENABLED=false
  #     # - CORE_PEER_GOSSIP_USELEADERELECTION=true
  #     # - CORE_PEER_GOSSIP_ORGLEADER=false
  #     # - CORE_PEER_PROFILE_ENABLED=true
  #     - CORE_PEER_FILESYSTEMPATH=/var/ledger
  #   working_dir: $HOME
  #   # command: peer node start --peer-chaincodedev=true
  #   command: peer node start

  #   volumes:
  #     # Folder with channel create tx file
  #     - ../../config:/var/hyperledger/channeltx
  #     # Map the folder with MSP for Peer
  #     - ../../crypto/crypto-config/peerOrganizations/budget.com/peers/budget-peer1/msp:/var/hyperledger/msp
  #     # Map the current folder to cfg
  #     - ../../config:/var/hyperledger/config
  #     - /var/run/:/host/var/run/
  #     # Ledger folder for the peer
  #     - ${HOME}/ledgers/budget-peer1.budget.com:/var/ledger
  #   depends_on: 
  #     - orderer.acme.com
  #   ports:
  #     - 8051:8051
  #     - 8052:8052
  #     - 8053:8053
  #   networks:
  #     - airline

  # tools:
  #   container_name: tools
  #   command: /bin/bash
  #   image: hyperledger/fabric-tools:$IMAGE_TAG
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_PEER_ADDRESS=acme-peer1.acme.com:7051
  #     - CORE_PEER_LOCALMSPID=AcmeMSP
  #     - FABRIC_CFG_PATH=/var/hyperledger/config
  #     - CORE_PEER_TLS_ENABLED=false
  #     - CORE_LOGGING_LEVEL=debug
  #   working_dir: /opt/scripts
  #   volumes:
  #     - ${GOPATH}:/opt/gopath
  #     # Folder with channel create tx file
  #     - ../../artefacts:/var/hyperledger/channeltx
  #     # Map the folder to root of all Fabric CA Client crypto
  #     - ../../crypto/crypto-config/peerOrganizations:/var/hyperledger/crypto
  #     # Map the current folder to cfg
  #     - ../../config:/var/hyperledger/config
  #     # VM docker stream folder mapping
  #     - /var/run/:/host/var/run/
  #     # Map the bins folder
  #     - ../../scripts:/opt/scripts
  #     # Map the nodechaincode folder
  #     - ../../tests:/opt/chaincode
  #   networks:
  #     - airline
  
  # Postgres
  # postgresql:
  #   container_name: postgresql
  #   image: postgres:9.5
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
      
  #   working_dir: $HOME
  #   volumes:
  #   # Folder with genesis block
  #   #- ..:/etc/postgresql/9.5/main
  #   - $PWD/explorer/bins:/home/vagrant/bins
  #   - /var/run/postgresql:/var/run/postgresql
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - airline
  
  # explorer:
  #   container_name: explorer
  #   image: acloudfan/hlf-explorer
  #   environment:
  #     - DATABASE_PASSWORD=postgres
  #     - DATABASE_HOST=postgresql
  #   volumes:
  #     - $PWD/explorer/bins:/home/vagrant/bins
  #     - $PWD/../crypto:/vagrant/network/crypto
  #     - /var/run/postgresql:/var/run/postgresql
  #   ports:
  #     - 8080:8080
  #   depends_on: 
  #     - postgresql
  #   networks:
  #     - airline