test:
  name: simple
  description: >-
    This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  workers:
    type: local
    number: 1
  rounds:
    - label: addSubject
      description: >-
        Test description for the opening of an account through the deployed
        chaincode
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: benchmarks/scenarios/simple/add.js
        arguments:
          money: 10000
monitor:
  type:
    - docker
  docker:
    name:
      - all
  interval: 1