version: "2"

services:
  caliper_2.1:
    container_name: caliper_2.1
    image: hyperledger/caliper:0.3.1
    command: launch master --caliper-fabric-gateway-usegateway --caliper-flow-only-test --caliper-fabric-gateway-discovery
    environment:
      - CORE_PEER_TLS_ENABLED=true
      - CALIPER_BIND_SUT=fabric:2.1.0
      - CALIPER_BENCHCONFIG=scenarios/access/config_createpolicy.yaml
      - CALIPER_NETWORKCONFIG=networks/fabric/network-config.yaml
    volumes:
      - ./:/hyperledger/caliper/workspace
    network_mode: host
